import type { SeverityLevel, SupportLevel, VerificationStatus, VerificationStatusLevel } from "./index";

/**
 * Negotiation Copilot domain types.
 *
 * A NegotiationDraft is generated for a single finding and is always a DRAFT for review. Every
 * legal reference inside it must come from the finding's existing Evidence Chain — the copilot
 * never introduces authority of its own.
 */

export type NegotiationTopic =
  | "training_bond"
  | "notice_period"
  | "intellectual_property"
  | "non_compete"
  | "dispute_resolution"
  | "confidentiality"
  | "termination"
  | "liability"
  | "general";

export type NegotiationGenerationMode = "grounded_template" | "ai_assisted";

export interface NegotiationLegalBasis {
  sourceId: string;
  citation: string;
  title: string;
  verificationStatus: VerificationStatusLevel | VerificationStatus;
  supportLevel?: SupportLevel;
  /** The Evidence Chain's own claim text for this source (never generated by the copilot). */
  claim?: string;
}

export interface NegotiationGrounding {
  documentQuote: string;
  section: string;
  pageNumber: number | null;
  legalBasis: NegotiationLegalBasis[];
  hasVerifiedAuthority: boolean;
  evidenceChainId?: string;
  uncertainties: string[];
}

export interface NegotiationMessageDraft {
  recipient: string;
  subject: string;
  body: string;
}

export interface NegotiationDraft {
  id: string;
  documentId: string;
  findingId: string;
  findingTitle: string;
  clauseId: string;
  clauseSection: string;
  pageNumber: number | null;
  severity: SeverityLevel;
  topic: NegotiationTopic;
  /** Plain-language explanation of what is being negotiated and why. */
  issueExplanation: string;
  /** Suggested replacement wording — a draft for review. */
  proposedClause: string;
  proposedClauseRationale: string;
  /** Fallback position / compromise if the primary ask is refused. */
  fallbackPosition: string;
  message: NegotiationMessageDraft;
  verifyBeforeAccepting: string[];
  grounding: NegotiationGrounding;
  generationMode: NegotiationGenerationMode;
  disclaimer: string;
  generatedAt: string;
}
