import type {
  ActionPlan,
  Clause,
  DetailedLawyerBrief,
  DocumentType,
  EvidenceChain,
  Finding,
  JurisdictionContext,
  KeyDate,
  LawyerBriefClause,
  LawyerBriefDate,
  LawyerBriefLegalContext,
  LawyerBriefQuestion,
} from "@/types";

import type { AiRunTracker } from "@/lib/ai/gemini";
import { documentTypeLabel } from "@/lib/documents/documentClassifier";

export interface DetailedLawyerBriefInput {
  documentId: string;
  documentTitle: string;
  documentType: string;
  date?: string;
  parties: string[];
  jurisdiction?: string;
  jurisdictionContext?: JurisdictionContext;
  documentSummary: string;
  findings: Finding[];
  clauses: Clause[];
  evidenceChains?: EvidenceChain[];
  keyDates?: KeyDate[];
  actionPlan?: ActionPlan;
  tracker?: AiRunTracker;
  /** True when the findings came from the rule-based fallback because AI analysis was unavailable. */
  heuristic?: boolean;
}

/**
 * Standard LawPilot Disclaimer for Lawyer Briefs.
 */
export const LAWYER_BRIEF_STANDARD_DISCLAIMER =
  "NOTICE & DISCLAIMER: This briefing document was generated by LawPilot to assist the user in preparing for an efficient consultation with a licensed legal practitioner. It organizes facts, clause excerpts, and verified statutory context identified in the submitted document. This document does NOT constitute formal legal advice, representation, or an attorney-client relationship. All legal interpretations and strategic decisions must be confirmed by a licensed attorney.";

/**
 * Deterministic synthesis of 1-2 page Lawyer Brief directly from verified data.
 * Adheres strictly to the 10-section structure with zero unverified claims.
 */
export function generateDeterministicLawyerBrief(
  input: DetailedLawyerBriefInput
): DetailedLawyerBrief {
  const findings = input.findings || [];
  const clauses = input.clauses || [];
  const evidenceChains = input.evidenceChains || [];
  const keyDates = input.keyDates || [];

  // 1. Matter Summary
  const highRiskCount = findings.filter(
    (f) => f.severity === "critical_attention" || f.severity === "high_attention"
  ).length;
  const knownJurisdiction = input.jurisdiction && !/^unknown/i.test(input.jurisdiction) ? input.jurisdiction : null;
  const docLabel = documentTypeLabel(input.documentType as DocumentType);
  const topTitles = findings
    .filter((f) => f.severity === "critical_attention" || f.severity === "high_attention")
    .slice(0, 3)
    .map((f) => f.title.replace(/\s+deserves review$/i, "").toLowerCase());
  const matterSummary = `Review of a ${docLabel} titled "${input.documentTitle}"${
    knownJurisdiction ? `, which appears to be governed by the law of ${knownJurisdiction}` : `. The document does not clearly establish which law governs it`
  }. ${
    input.heuristic ? "A rule-based (heuristic) scan, run because AI analysis was unavailable, flagged" : "Analysis identified"
  } ${findings.length} provision${findings.length === 1 ? "" : "s"} of interest${
    highRiskCount > 0 ? `, including ${highRiskCount} elevated-risk term${highRiskCount === 1 ? "" : "s"}${topTitles.length ? ` (${topTitles.join("; ")})` : ""}` : ""
  }. The reader is seeking legal review to assess enforceability, identify drafting asymmetries, and prepare negotiation points before relying on the agreement.`;

  // 2. User Concerns
  const userConcerns = findings.map(
    (f) => `[${f.severity.toUpperCase().replace("_", " ")}] ${f.title}: ${f.plainEnglishSummary || f.whyItMatters || f.description}`
  );

  // 3. Relevant Clauses (Deduplicated by clauseId to guarantee unique attorney review items and React keys)
  const seenClauseIds = new Set<string>();
  const relevantClauses: LawyerBriefClause[] = [];

  findings.forEach((f, idx) => {
    const clauseSec = f.clauseReference?.section || f.evidence?.section || `Section ${idx + 1}`;
    const rawClauseId = f.clauseReference?.clauseId || f.clauseId || f.evidence?.clauseId || `clause-${idx + 1}`;
    const clauseId = seenClauseIds.has(rawClauseId) ? `${rawClauseId}-${idx + 1}` : rawClauseId;

    if (seenClauseIds.has(clauseId)) return;
    seenClauseIds.add(clauseId);

    const matchingClause = clauses.find(
      (c) => c.id === rawClauseId || c.section === clauseSec || c.sectionNumber === clauseSec
    );

    const excerpt = matchingClause?.rawText || matchingClause?.clauseText || f.evidence?.quotedText || f.clauseReference?.exactQuote || f.plainEnglishSummary || f.description;
    const plainEnglish = f.plainEnglishSummary || matchingClause?.plainEnglish || f.whyItMatters || f.description;

    relevantClauses.push({
      clauseId,
      section: clauseSec,
      pageNumber: f.clauseReference?.pageNumber ?? f.evidence?.pageNumber ?? matchingClause?.pageNumber ?? null,
      excerpt,
      plainEnglish,
      importance: f.severity,
    });
  });

  // 4. Verified Legal Context (Only verified sources from evidence chains)
  const verifiedLegalContext: LawyerBriefLegalContext[] = [];
  const seenCitations = new Set<string>();

  evidenceChains.forEach((chain) => {
    chain.legalSources.forEach((src) => {
      if (src.verificationStatus === "verified" || src.verificationStatus === "partially_verified") {
        const citationKey = `${src.citation}-${src.jurisdiction}`;
        if (!seenCitations.has(citationKey)) {
          seenCitations.add(citationKey);
          verifiedLegalContext.push({
            issueTitle: chain.finding.title,
            sourceTitle: src.title,
            citation: src.citation,
            jurisdiction: src.jurisdiction,
            explanation: src.relevance || chain.legalClaims[0]?.claim || chain.legalClaims[0]?.statement || "",
            verificationStatus: src.verificationStatus,
          });
        }
      }
    });
  });

  // Legal context is ONLY what the evidence chains verified. If none is linked, the brief says so
  // (see the UI) rather than inventing authorities for the document's apparent jurisdiction.

  // 5. What Remains Uncertain
  const uncertaintiesSet = new Set<string>();
  evidenceChains.forEach((c) => {
    (c.uncertainties || []).forEach((u) => uncertaintiesSet.add(u));
  });

  if (uncertaintiesSet.size === 0) {
    findings.forEach((f) => (f.uncertainties || []).forEach((u) => uncertaintiesSet.add(u)));
  }
  if (uncertaintiesSet.size === 0) {
    uncertaintiesSet.add("Facts outside the written agreement (how its terms are applied in practice) are not stated in the document.");
    uncertaintiesSet.add("Which law governs, and how it treats the flagged terms, should be confirmed by counsel.");
  }
  const whatRemainsUncertain = Array.from(uncertaintiesSet);

  // 6. Documents Available
  const isEmploymentDoc = input.documentType === "employment_agreement";
  const documentsAvailable = [
    `Complete signed or proposed agreement (${input.documentTitle})`,
    ...(isEmploymentDoc
      ? [
          "Formal written job offer letter and salary notification",
          "Company policies or handbook (if incorporated by reference)",
        ]
      : ["Any amendments, schedules, annexures or side letters"]),
    "Written correspondence with the other party about the flagged terms",
    "Any payment records, invoices or receipts relevant to the amounts in the agreement",
  ];

  // 7. High-Value Questions for Counsel
  const questionsForCounsel: LawyerBriefQuestion[] = findings.map((f) => {
    const sec = f.clauseReference?.section || f.evidence?.section || "the applicable section";
    const lower = f.title.toLowerCase();

    let q = `What revisions should be requested for ${sec} to reduce exposure, and are they realistic to negotiate?`;
    const ctx = f.plainEnglishSummary || f.whyItMatters || f.description;

    if (
      lower.includes("non-compete") ||
      lower.includes("restrictive") ||
      lower.includes("competing") ||
      lower.includes("restriction") ||
      lower.includes("solicit") ||
      f.category.toLowerCase().includes("restrictive")
    ) {
      q = `Is the restriction in ${sec} enforceable under the governing law, and can its duration, geographic scope and covered activities be narrowed?`;
    } else if (lower.includes("training") || lower.includes("reimbursement") || lower.includes("clawback") || lower.includes("exit financial")) {
      q = `Is the repayment or payment obligation in ${sec} enforceable under the governing law, and should it reduce pro-rata or be tied to documented costs?`;
    } else if (lower.includes("invention") || lower.includes("intellectual property") || /ip/.test(lower) || f.category.toLowerCase().includes("intellectual")) {
      q = `How should ${sec} be revised to add a carve-out for pre-existing work and anything created independently?`;
    } else if (lower.includes("arbitration") || lower.includes("dispute") || lower.includes("court forum")) {
      q = `Who bears forum and arbitrator costs under ${sec}, and is that allocation enforceable?`;
    } else if (lower.includes("notice")) {
      q = `Can the notice terms in ${sec} be made mutual, and can they be shortened or waived by agreement?`;
    }

    return {
      findingId: f.id,
      clauseReference: sec,
      question: q,
      context: ctx,
    };
  });

  // 8. Important Dates
  const importantDates: LawyerBriefDate[] = keyDates.map((kd) => ({
    label: kd.label,
    date: kd.date ?? null,
    noticePeriodDays: kd.noticePeriodDays ?? null,
    description: kd.description || kd.label,
    isDeadline: kd.isDeadline ?? (!!kd.noticePeriodDays || !!kd.date),
  }));

  if (importantDates.length === 0) {
    importantDates.push({
      label: "No dated deadlines identified",
      description: "The analysis did not find explicit dates or notice windows. Confirm any timing requirements with the other party.",
      isDeadline: false,
    });
  }

  return {
    id: `detailed-brief-${Date.now()}`,
    generatedAt: new Date().toISOString(),
    matterSummary,
    document: {
      title: input.documentTitle,
      documentType: input.documentType,
      date: input.date || new Date().toISOString().split("T")[0],
      parties: input.parties && input.parties.length > 0 ? input.parties : ["Not identified in the document"],
      jurisdiction: input.jurisdiction || (input.jurisdictionContext && input.jurisdictionContext.country !== "Unknown" ? input.jurisdictionContext.country : "Not established by the document"),
      jurisdictionContext: input.jurisdictionContext,
    },
    jurisdictionContext: input.jurisdictionContext,
    userConcerns,
    relevantClauses,
    verifiedLegalContext,
    whatRemainsUncertain,
    documentsAvailable,
    questionsForCounsel,
    importantDates,
    disclaimer: LAWYER_BRIEF_STANDARD_DISCLAIMER,
  };
}
