"use client";

import React, { useState } from "react";
import type { DetailedLawyerBrief, NegotiationDraft } from "@/types";
import { useSavedNegotiationDrafts } from "@/lib/negotiation/negotiationStore";
import { getBriefVerificationState, VERIFICATION_TONE_CLASSES } from "@/lib/analysis/verificationState";
import { formatJurisdictionBadge } from "@/lib/jurisdiction/jurisdictionDetector";

interface LawyerBriefProps {
  brief: DetailedLawyerBrief;
  /** Document whose saved Negotiation Copilot drafts are appended for counsel review. */
  documentId?: string;
  onNavigateToActionPlan?: () => void;
  onSelectFinding?: (findingId: string) => void;
}

/**
 * Pure generator for formatted Lawyer Brief Markdown representation.
 * Exported so regression tests can verify verbatim heading and verification text.
 */
export function generateLawyerBriefMarkdown(
  brief: DetailedLawyerBrief,
  negotiationDrafts: NegotiationDraft[] = []
): string {
  const verification = brief.verificationState || getBriefVerificationState(brief);
  const isUnverified = verification.tone === "unverified" || (brief.verifiedLegalContext?.length ?? 0) === 0;
  const effectiveJurisdiction =
    brief.document.jurisdiction ||
    (brief.jurisdictionContext ? formatJurisdictionBadge(brief.jurisdictionContext) : "Unspecified");

  const lines: string[] = [];
  lines.push(`# LAWYER BRIEF: ${brief.document.title.toUpperCase()}`);
  lines.push(`**Generated by LawPilot:** ${new Date(brief.generatedAt).toLocaleString()}`);
  lines.push(`**Jurisdiction:** ${effectiveJurisdiction}\n`);

  lines.push(`## 1. MATTER SUMMARY`);
  lines.push(`${brief.matterSummary}\n`);

  lines.push(`## 2. DOCUMENT INFORMATION`);
  lines.push(`- **Title:** ${brief.document.title}`);
  lines.push(`- **Document Type:** ${brief.document.documentType}`);
  lines.push(`- **Date:** ${brief.document.date}`);
  lines.push(`- **Parties:** ${brief.document.parties.join(", ")}`);
  lines.push(`- **Jurisdiction:** ${effectiveJurisdiction}\n`);

  lines.push(`## 3. CLIENT CONCERNS & IDENTIFIED RISKS`);
  brief.userConcerns.forEach((c) => lines.push(`- ${c}`));
  lines.push("");

  lines.push(`## 4. RELEVANT CLAUSES FOR REVIEW`);
  brief.relevantClauses.forEach((c) => {
    lines.push(`### ${c.section} ${c.pageNumber ? `(Page ${c.pageNumber})` : ""} [${c.importance.toUpperCase().replace("_", " ")}]`);
    lines.push(`> "${c.excerpt}"\n`);
    lines.push(`**Plain-English Summary:** ${c.plainEnglish}\n`);
  });

  const section5Heading = isUnverified
    ? "5. LEGAL CONTEXT & AUTHORITIES"
    : "5. VERIFIED LEGAL CONTEXT & AUTHORITIES";
  lines.push(`## ${section5Heading}`);
  if (brief.verifiedLegalContext.length === 0) {
    lines.push(`- Not verified: no legal source could be verified for this document in the stated jurisdiction (${effectiveJurisdiction}); insufficient legal context to provide authoritative statutory verification.`);
  }
  brief.verifiedLegalContext.forEach((lc) => {
    lines.push(`- **${lc.issueTitle}**: *${lc.sourceTitle}* (${lc.citation}, ${lc.jurisdiction})`);
    lines.push(`  ${lc.explanation} [Status: ${lc.verificationStatus}]`);
  });
  lines.push("");

  lines.push(`## 6. WHAT REMAINS UNCERTAIN`);
  brief.whatRemainsUncertain.forEach((u) => lines.push(`- ${u}`));
  lines.push("");

  lines.push(`## 7. DOCUMENTS AVAILABLE`);
  brief.documentsAvailable.forEach((d) => lines.push(`- [ ] ${d}`));
  lines.push("");

  lines.push(`## 8. HIGH-VALUE QUESTIONS FOR COUNSEL`);
  brief.questionsForCounsel.forEach((q, idx) => {
    lines.push(`${idx + 1}. **${q.clauseReference}:** ${q.question}`);
    lines.push(`   *Context:* ${q.context}`);
  });
  lines.push("");

  if (negotiationDrafts.length > 0) {
    lines.push(`## 8a. PROPOSED NEGOTIATION POSITIONS (DRAFTS FOR COUNSEL REVIEW)`);
    lines.push(`*Generated by LawPilot's Negotiation Copilot from the findings and Evidence Chains above. Not legal advice; wording has not been checked for legal correctness or enforceability.*\n`);
    negotiationDrafts.forEach((d, idx) => {
      lines.push(`### N${idx + 1}. ${d.clauseSection}${d.pageNumber ? ` (Page ${d.pageNumber})` : ""}: ${d.findingTitle}`);
      lines.push(`**Issue:** ${d.issueExplanation}\n`);
      lines.push(`**Proposed revision (draft):**`);
      lines.push(`> ${d.proposedClause}\n`);
      lines.push(`**Fallback position:** ${d.fallbackPosition}\n`);
      if (d.grounding.legalBasis.length > 0) {
        lines.push(`**Linked sources (from Evidence Chain):** ${d.grounding.legalBasis.map((b) => `${b.citation} [${b.verificationStatus}]`).join("; ")}\n`);
      } else {
        lines.push(`**Linked sources:** None verified — based on contract text only.\n`);
      }
      lines.push(`**Please confirm:**`);
      d.verifyBeforeAccepting.forEach((v) => lines.push(`- ${v}`));
      lines.push("");
    });
  }

  lines.push(`## 9. IMPORTANT DATES & DEADLINES`);
  brief.importantDates.forEach((d) => {
    lines.push(`- **${d.label}:** ${d.date || "Trigger-based"}${d.noticePeriodDays ? ` (${d.noticePeriodDays} days notice required)` : ""} — ${d.description}`);
  });
  lines.push("");

  lines.push(`## 10. DISCLAIMER`);
  lines.push(`${brief.disclaimer}\n`);

  return lines.join("\n");
}

export const LawyerBriefView: React.FC<LawyerBriefProps> = ({
  brief,
  documentId,
  onNavigateToActionPlan,
  onSelectFinding,
}) => {
  const negotiationDrafts = useSavedNegotiationDrafts(documentId);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const verification = brief.verificationState || getBriefVerificationState(brief);
  const isUnverified = verification.tone === "unverified" || (brief.verifiedLegalContext?.length ?? 0) === 0;
  const effectiveJurisdiction =
    brief.document.jurisdiction ||
    (brief.jurisdictionContext ? formatJurisdictionBadge(brief.jurisdictionContext) : "Unspecified");

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3000);
  };

  // 1. Print handler
  const handlePrint = () => {
    window.print();
  };

  // 2. Generate formatted Markdown representation
  const generateMarkdown = (): string => generateLawyerBriefMarkdown(brief, negotiationDrafts);

  // 3. Copy to clipboard
  const handleCopy = () => {
    const md = generateMarkdown();
    navigator.clipboard.writeText(md);
    showToast("Complete Lawyer Brief copied to clipboard as Markdown!");
  };

  // 4. Download text file
  const handleDownload = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const safeTitle = brief.document.title.replace(/[^a-z0-9_-]/gi, "_").toLowerCase();
    a.download = `Lawyer_Brief_${safeTitle}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast("Brief downloaded successfully!");
  };

  return (
    <div className="space-y-6">
      {/* Toast Notification */}
      {toastMessage && (
        <div className="fixed bottom-6 right-6 z-50 px-4 py-3 bg-emerald-950 border border-emerald-500/50 text-emerald-200 rounded-lg shadow-xl shadow-black/50 text-sm font-medium flex items-center gap-2 print:hidden animate-in fade-in slide-in-from-bottom-3 duration-200">
          <svg className="w-4 h-4 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
          </svg>
          {toastMessage}
        </div>
      )}

      {/* Screen Control Header (Hidden during Print) */}
      <div className="p-6 rounded-2xl bg-gradient-to-br from-slate-900 via-slate-900 to-indigo-950/40 border border-indigo-500/20 shadow-xl print:hidden flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
              LEGAL COUNSEL READY
            </span>
            <span className="text-xs text-slate-400 font-medium">
              1-2 Page Structured Attorney Intake Brief
            </span>
          </div>
          <h2 className="text-2xl font-bold text-white tracking-tight">
            Lawyer Brief
          </h2>
          <p className="text-sm text-slate-300 mt-1 max-w-xl">
            {isUnverified
              ? "A concise, high-efficiency consultation briefing synthesizing document intelligence, factual clause analysis, and key questions to minimize attorney billable hours."
              : "A concise, high-efficiency consultation briefing synthesizing document intelligence, verified legal context, and key questions to minimize attorney billable hours."}
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap items-center gap-2">
          {onNavigateToActionPlan && (
            <button
              onClick={onNavigateToActionPlan}
              className="px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 text-xs font-medium transition flex items-center gap-1.5 min-h-[40px]"
            >
              ← Action Plan
            </button>
          )}

          <button
            onClick={handleCopy}
            className="px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 text-xs font-medium transition flex items-center gap-1.5 shadow-sm min-h-[40px]"
            title="Copy as Markdown"
          >
            <svg className="w-4 h-4 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
            </svg>
            Copy Brief (MD)
          </button>

          <button
            onClick={handleDownload}
            className="px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 text-xs font-medium transition flex items-center gap-1.5 shadow-sm min-h-[40px]"
            title="Download Markdown file"
          >
            <svg className="w-4 h-4 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download
          </button>

          <button
            onClick={handlePrint}
            className="px-4 py-2 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white text-xs font-semibold shadow-lg shadow-emerald-600/20 transition flex items-center gap-2 min-h-[40px]"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            <span>Print Brief</span>
          </button>
        </div>
      </div>

      {/* 
        DOCUMENT BRIEF CONTAINER 
        Styled for on-screen elegance and print media perfection.
      */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-4 sm:p-8 lg:p-12 shadow-2xl space-y-6 sm:space-y-8 print:bg-white print:text-black print:border-none print:shadow-none print:p-0 print:space-y-6">
        {/* Document Header */}
        <div className="border-b border-slate-800 pb-6 print:border-black/20">
          <div className="flex items-center justify-between">
            <div className="text-xs uppercase tracking-widest text-indigo-400 font-bold print:text-gray-600">
              LawPilot • Attorney Preparation Brief
            </div>
            <div className="text-xs text-slate-400 print:text-gray-600">
              Date: {new Date(brief.generatedAt).toLocaleDateString()}
            </div>
          </div>
          <h1 className="text-2xl lg:text-3xl font-bold text-white mt-2 print:text-black">
            {brief.document.title}
          </h1>
          <div className="flex flex-wrap items-center gap-4 text-xs text-slate-300 mt-2 print:text-gray-700">
            <span><strong>Parties:</strong> {brief.document.parties.join(" & ")}</span>
            <span>•</span>
            <span><strong>Type:</strong> {brief.document.documentType}</span>
            <span>•</span>
            <span><strong>Governing Law:</strong> {effectiveJurisdiction}</span>
          </div>
        </div>

        {/* Section 1: Matter Summary */}
        <section className="space-y-2">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 print:text-gray-700 flex items-center gap-2">
            <span className="w-5 h-5 rounded-full bg-slate-800 text-indigo-400 flex items-center justify-center text-[10px] print:hidden">1</span>
            Matter Summary & Stance
          </h3>
          <p className="text-sm text-slate-200 leading-relaxed print:text-gray-900 bg-slate-800/40 p-4 rounded-xl border border-slate-800/80 print:bg-transparent print:p-0 print:border-none">
            {brief.matterSummary}
          </p>
        </section>

        {/* Section 2: Document Information Grid */}
        <section className="space-y-2">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 print:text-gray-700 flex items-center gap-2">
            <span className="w-5 h-5 rounded-full bg-slate-800 text-indigo-400 flex items-center justify-center text-[10px] print:hidden">2</span>
            Document Metadata
          </h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-xs">
            <div className="p-3 rounded-lg bg-slate-800/30 border border-slate-800 print:border-gray-300 print:p-2">
              <div className="text-slate-400 print:text-gray-500">Document Type</div>
              <div className="font-semibold text-white print:text-black mt-0.5">{brief.document.documentType}</div>
            </div>
            <div className="p-3 rounded-lg bg-slate-800/30 border border-slate-800 print:border-gray-300 print:p-2">
              <div className="text-slate-400 print:text-gray-500">Effective Date</div>
              <div className="font-semibold text-white print:text-black mt-0.5">{brief.document.date}</div>
            </div>
            <div className="p-3 rounded-lg bg-slate-800/30 border border-slate-800 print:border-gray-300 print:p-2">
              <div className="text-slate-400 print:text-gray-500">Jurisdiction</div>
              <div className="font-semibold text-white print:text-black mt-0.5">{effectiveJurisdiction}</div>
            </div>
            <div className="p-3 rounded-lg bg-slate-800/30 border border-slate-800 print:border-gray-300 print:p-2">
              <div className="text-slate-400 print:text-gray-500">Parties Involved</div>
              <div className="font-semibold text-white print:text-black mt-0.5">{brief.document.parties.length} Identified</div>
            </div>
          </div>
        </section>

        {/* Section 3: Client Concerns */}
        <section className="space-y-2">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 print:text-gray-700 flex items-center gap-2">
            <span className="w-5 h-5 rounded-full bg-slate-800 text-indigo-400 flex items-center justify-center text-[10px] print:hidden">3</span>
            Client Concerns & Key Risks
          </h3>
          <ul className="space-y-1.5 text-xs text-slate-300 print:text-gray-800">
            {brief.userConcerns.map((concern, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="text-rose-400 print:text-black font-bold">•</span>
                <span>{concern}</span>
              </li>
            ))}
          </ul>
        </section>

        {/* Section 4: Relevant Clauses with Excerpt & Summary */}
        <section className="space-y-3">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 print:text-gray-700 flex items-center gap-2">
            <span className="w-5 h-5 rounded-full bg-slate-800 text-indigo-400 flex items-center justify-center text-[10px] print:hidden">4</span>
            Relevant Clauses For Attorney Review
          </h3>
          <div className="space-y-3">
            {brief.relevantClauses.map((clause, idx) => (
              <div
                key={clause.clauseId ? `${clause.clauseId}-${idx}` : `clause-${idx}`}
                className="p-4 rounded-xl bg-slate-800/20 border border-slate-800 print:border-gray-300 print:bg-transparent print:p-2 space-y-2"
              >
                <div className="flex items-center justify-between text-xs">
                  <div className="font-bold text-white print:text-black flex items-center gap-2">
                    <span>{clause.section}</span>
                    {clause.pageNumber && (
                      <span className="text-slate-400 print:text-gray-500 font-normal">
                        (Page {clause.pageNumber})
                      </span>
                    )}
                  </div>
                  <span className="px-2 py-0.5 rounded bg-rose-500/10 text-rose-400 border border-rose-500/20 text-[10px] font-semibold uppercase print:border print:text-black">
                    {clause.importance.replace("_", " ")}
                  </span>
                </div>

                <div className="p-2.5 rounded bg-slate-900/80 border-l-2 border-indigo-500 text-xs italic text-slate-300 print:bg-gray-50 print:text-black print:border-gray-400">
                  &ldquo;{clause.excerpt}&rdquo;
                </div>

                <div className="text-xs text-slate-300 print:text-gray-800">
                  <strong className="text-slate-400 print:text-black">Plain-English Translation:</strong> {clause.plainEnglish}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Section 5: Legal Context & Authorities */}
        <section className="space-y-2">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 print:text-gray-700 flex items-center gap-2">
              <span className="w-5 h-5 rounded-full bg-slate-800 text-indigo-400 flex items-center justify-center text-[10px] print:hidden">5</span>
              {isUnverified ? "Legal Context & Authorities" : "Verified Legal Context & Authorities"}
            </h3>
            <span
              className={`text-[10px] font-semibold px-2 py-0.5 rounded ${VERIFICATION_TONE_CLASSES[verification.tone].pill}`}
              data-testid="brief-verification-badge"
            >
              {verification.label}
            </span>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {brief.verifiedLegalContext.length === 0 && (
              <p className="md:col-span-2 text-xs text-slate-400 print:text-gray-700">
                Not verified: no legal source could be verified for this document in the stated jurisdiction ({effectiveJurisdiction}); insufficient legal context to provide authoritative statutory verification. Analysis is based on factual agreement clauses.
              </p>
            )}
            {brief.verifiedLegalContext.map((lc, idx) => (
              <div
                key={idx}
                className="p-3.5 rounded-xl bg-slate-800/30 border border-slate-800 print:border-gray-300 text-xs space-y-1"
              >
                <div className="flex items-center justify-between font-semibold">
                  <span className="text-indigo-300 print:text-black">{lc.issueTitle}</span>
                  {lc.verificationStatus === "verified" ? (
                    <span className="text-[10px] text-emerald-400 print:text-gray-600">✓ Verified</span>
                  ) : (
                    <span className="text-[10px] text-amber-400 print:text-gray-600">Partially verified</span>
                  )}
                </div>
                <div className="font-mono text-[11px] text-slate-400 print:text-gray-600">
                  {lc.citation} ({lc.jurisdiction})
                </div>
                <p className="text-slate-300 print:text-gray-800 pt-1 leading-relaxed">
                  {lc.explanation}
                </p>
              </div>
            ))}
          </div>
        </section>

        {/* Section 6: What Remains Uncertain */}
        <section className="space-y-2">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 print:text-gray-700 flex items-center gap-2">
            <span className="w-5 h-5 rounded-full bg-slate-800 text-indigo-400 flex items-center justify-center text-[10px] print:hidden">6</span>
            What Remains Uncertain (Factual Dependencies)
          </h3>
          <ul className="space-y-1 text-xs text-slate-300 print:text-gray-800">
            {brief.whatRemainsUncertain.map((item, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="text-amber-400 print:text-black font-bold">?</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </section>

        {/* Section 7: Documents Available for Counsel */}
        <section className="space-y-2">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 print:text-gray-700 flex items-center gap-2">
            <span className="w-5 h-5 rounded-full bg-slate-800 text-indigo-400 flex items-center justify-center text-[10px] print:hidden">7</span>
            Supporting Documents Available / Recommended
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-xs text-slate-300 print:text-gray-800">
            {brief.documentsAvailable.map((doc, idx) => (
              <div key={idx} className="flex items-center gap-2 p-2 rounded bg-slate-800/20 border border-slate-800/60 print:border-none print:p-0">
                <span className="text-indigo-400 print:text-black">📁</span>
                <span>{doc}</span>
              </div>
            ))}
          </div>
        </section>

        {/* Section 8: High-Value Questions for Counsel */}
        <section className="space-y-3">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 print:text-gray-700 flex items-center gap-2">
            <span className="w-5 h-5 rounded-full bg-slate-800 text-indigo-400 flex items-center justify-center text-[10px] print:hidden">8</span>
            High-Value Consultation Questions for Counsel
          </h3>
          <div className="space-y-2.5">
            {brief.questionsForCounsel.map((q, idx) => (
              <div
                key={idx}
                className="p-3.5 rounded-xl bg-indigo-950/20 border border-indigo-500/20 print:border-gray-300 print:bg-transparent print:p-2 text-xs space-y-1"
              >
                <div className="flex items-center justify-between">
                  <span className="font-semibold text-indigo-300 print:text-black">
                    Q{idx + 1} ({q.clauseReference})
                  </span>
                  {onSelectFinding && (
                    <button
                      onClick={() => onSelectFinding(q.findingId)}
                      className="text-[11px] text-indigo-400 hover:text-indigo-300 print:hidden underline"
                    >
                      View Finding
                    </button>
                  )}
                </div>
                <p className="font-medium text-white print:text-black leading-relaxed">
                  {q.question}
                </p>
                <p className="text-slate-400 print:text-gray-600 text-[11px]">
                  <em>Background:</em> {q.context}
                </p>
              </div>
            ))}
          </div>
        </section>

        {/* Section 8a: Negotiation Copilot drafts saved by the user */}
        {negotiationDrafts.length > 0 && (
          <section className="space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 print:text-gray-700 flex items-center gap-2">
              <span className="w-5 h-5 rounded-full bg-slate-800 text-indigo-400 flex items-center justify-center text-[10px] print:hidden">8a</span>
              Proposed Negotiation Positions — Drafts for Counsel Review
            </h3>
            <p className="text-[11px] text-amber-300/90 print:text-gray-700">
              Generated by LawPilot&apos;s Negotiation Copilot from the findings and Evidence Chains in this brief. Not
              legal advice — the wording has not been checked for legal correctness or enforceability.
            </p>
            <div className="space-y-2.5">
              {negotiationDrafts.map((d, idx) => (
                <div
                  key={d.id}
                  className="p-3.5 rounded-xl bg-slate-800/30 border border-slate-700/60 print:border-gray-300 print:bg-transparent print:p-2 text-xs space-y-2"
                >
                  <div className="flex items-center justify-between gap-2">
                    <span className="font-semibold text-indigo-300 print:text-black">
                      N{idx + 1} ({d.clauseSection}{d.pageNumber ? `, p.${d.pageNumber}` : ""})
                    </span>
                    {onSelectFinding && (
                      <button
                        onClick={() => onSelectFinding(d.findingId)}
                        className="text-[11px] text-indigo-400 hover:text-indigo-300 print:hidden underline"
                      >
                        View Finding
                      </button>
                    )}
                  </div>
                  <p className="font-medium text-white print:text-black leading-relaxed">{d.findingTitle}</p>
                  <div className="p-2.5 rounded-lg border border-dashed border-indigo-500/40 print:border-gray-400 text-slate-200 print:text-black leading-relaxed">
                    <span className="block text-[10px] font-semibold uppercase tracking-wider text-amber-300 print:text-gray-700 mb-1">
                      Proposed revision · draft
                    </span>
                    {d.proposedClause}
                  </div>
                  <p className="text-slate-300 print:text-gray-800">
                    <em>Fallback:</em> {d.fallbackPosition}
                  </p>
                  <p className="text-slate-400 print:text-gray-600 text-[11px]">
                    <em>Linked sources:</em>{" "}
                    {d.grounding.legalBasis.length > 0
                      ? d.grounding.legalBasis.map((b) => `${b.citation} (${String(b.verificationStatus).replace(/_/g, " ")})`).join("; ")
                      : "None verified — based on contract text only."}
                  </p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Section 9: Important Dates & Deadlines */}
        <section className="space-y-2">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 print:text-gray-700 flex items-center gap-2">
            <span className="w-5 h-5 rounded-full bg-slate-800 text-indigo-400 flex items-center justify-center text-[10px] print:hidden">9</span>
            Important Dates & Deadlines
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-xs">
            {brief.importantDates.map((d, idx) => (
              <div
                key={idx}
                className="p-3 rounded-lg bg-slate-800/30 border border-slate-800 print:border-gray-300 text-slate-300 print:text-gray-800 space-y-0.5"
              >
                <div className="flex items-center justify-between font-semibold">
                  <span className="text-white print:text-black">{d.label}</span>
                  {d.isDeadline && (
                    <span className="text-[10px] px-1.5 py-0.2 rounded bg-rose-500/20 text-rose-400 print:border print:text-black">
                      Deadline
                    </span>
                  )}
                </div>
                {d.date && <div className="text-indigo-400 print:text-black font-mono text-[11px]">{d.date}</div>}
                {d.noticePeriodDays && (
                  <div className="text-amber-400 print:text-black text-[11px]">Notice Window: {d.noticePeriodDays} Days</div>
                )}
                <div className="text-slate-400 print:text-gray-600 text-[11px]">{d.description}</div>
              </div>
            ))}
          </div>
        </section>

        {/* Section 10: Prominent Disclaimer */}
        <section className="pt-4 border-t border-slate-800 print:border-gray-400">
          <div className="p-4 rounded-xl bg-slate-950/60 border border-slate-800 text-xs text-slate-400 print:text-gray-600 print:border-none print:p-0 space-y-1">
            <div className="font-bold text-slate-300 print:text-black uppercase tracking-wider text-[11px]">
              Section 10 • Notice & Informational Disclaimer
            </div>
            <p className="leading-relaxed">
              {brief.disclaimer}
            </p>
          </div>
        </section>
      </div>
    </div>
  );
};
